# Generated by Django 5.0.6 on 2024-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_movie_genre_movie_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='POSTER1/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
